[package]
name = "dbmeter"
version = "0.1.13"
authors = ["Anton Okolelov <okoanton@yandex.ru>", "Oleg Gritsak <hack3p@gmail.com>"]

[dependencies]
postgres = "0.15"
chrono = "0.4"
dotenv = "0.10"
lazy_static = "1.0"